apiVersion: troubleshoot.sh/v1beta2
kind: HostPreflight
metadata:
  name: fsperf
spec:
  collectors:
    - filesystemPerformance:
        collectorName: etcd-perf
        directory: /var/lib/etcd
        fileSize: 22Mi
        operationSizeBytes: 2300
        datasync: true
  analyzers:
    - filesystemPerformance:
        collectorName: etcd-perf
        outcomes:
          - pass:
              when: "p99 < 3ms"
              message: Write latency is great!
          - pass:
              when: "p99 < 5ms"
              message: Write latency is ok
          - warn:
              when: "p99 < 8ms"
              message: Write latency is high
          - fail:
              when: "p99 >= 8ms"
              message: Write latency is too high
