project_name: troubleshoot
release:
  github:
    owner: replicatedhq
    name: troubleshoot
builds:
  - id: collector
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    main: cmd/collector/main.go
    ldflags: -s -w
      -X github.com/replicatedhq/troubleshoot/pkg/version.version={{.Version}}
      -X github.com/replicatedhq/troubleshoot/pkg/version.gitSHA={{.Commit}}
      -X github.com/replicatedhq/troubleshoot/pkg/version.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: collector
    hooks: {}
  - id: preflight
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    main: cmd/preflight/main.go
    ldflags: -s -w
      -X github.com/replicatedhq/troubleshoot/pkg/version.version={{.Version}}
      -X github.com/replicatedhq/troubleshoot/pkg/version.gitSHA={{.Commit}}
      -X github.com/replicatedhq/troubleshoot/pkg/version.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: preflight
    hooks: {}
  - id: troubleshoot
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    main: cmd/troubleshoot/main.go
    ldflags: -s -w
      -X github.com/replicatedhq/troubleshoot/pkg/version.version={{.Version}}
      -X github.com/replicatedhq/troubleshoot/pkg/version.gitSHA={{.Commit}}
      -X github.com/replicatedhq/troubleshoot/pkg/version.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: troubleshoot
    hooks: {}
  - id: manager
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    main: cmd/manager/main.go
    ldflags: -s -w
      -X github.com/replicatedhq/troubleshoot/pkg/version.version={{.Version}}
      -X github.com/replicatedhq/troubleshoot/pkg/version.gitSHA={{.Commit}}
      -X github.com/replicatedhq/troubleshoot/pkg/version.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: manager
    hooks: {}
archives:
  - id: preflight
    builds:
      - preflight
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}-{{ .Major }}.{{ .Minor }}.{{ .Patch }}'
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
  - id: troubleshoot
    builds:
      - troubleshoot
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}-{{ .Major }}.{{ .Minor }}.{{ .Patch }}'
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
dockers:
  - dockerfile: ./deploy/Dockerfile.troubleshoot
    image_templates:
      - "replicated/troubleshoot:latest"
      - "replicated/troubleshoot:{{ .Major }}"
      - "replicated/troubleshoot:{{ .Major }}.{{ .Minor }}"
      - "replicated/troubleshoot:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    binaries:
      - collector
      - troubleshoot
      - preflight
  - dockerfile: ./deploy/Dockerfile.troubleshoot
    image_templates:
      - "replicated/preflight:latest"
      - "replicated/preflight:{{ .Major }}"
      - "replicated/preflight:{{ .Major }}.{{ .Minor }}"
      - "replicated/preflight:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    binaries:
      - collector
      - troubleshoot
      - preflight
  - dockerfile: ./deploy/Dockerfile.manager
    image_templates:
      - "replicated/troubleshoot-manager:latest"
      - "replicated/troubleshoot-manager:{{ .Major }}"
      - "replicated/troubleshoot-manager:{{ .Major }}.{{ .Minor }}"
      - "replicated/troubleshoot-manager:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    binaries:
      - manager
