apiVersion: troubleshoot.replicated.com/v1beta1
kind: Preflight
metadata:
  name: preflight-sample
spec:
  analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.14.0"
              message: You need more kubernetes
              uri: https://help.replicated.com/kubernetes-version
          - warn:
              when: "< 1.15.0"
              message: You have barely enough kubernetes
              uri: https://help.replicated.com/kubernetes-version
          - pass:
              message: Good job keeping k8s current
    - storageClass:
        checkName: Required storage classes
        storageClassName: "microk8s-hostpath"
        outcomes:
          - fail:
              message: The micr0k8s storage class thing was not found
          - pass:
              message: All good on storage classes
    - secret:
        checkName: PG URI
        secretName: postgres
        namespace: default
        key: uri
        outcomes:
          - fail:
              message: You don't have a pg uri secret
          - pass:
              message: Probably a green light connecting to pg

    # - manifests:
    #     - secret:
    #         namespace: default
    #         name: shhh
    #         key: top-secret
    #       fail:
    #         message: The top secret secret is missing
    #       pass:
    #         message: You know the secret
    - ingress:
        namespace: default
        ingressName: connect-to-me
        outcomes:
          - fail:
              message: The ingress isn't ingressing
          - pass:
              message: All systems ok on ingress
    # - imagePullSecret:
    #     name: replicated
    #     namespace: my-app
    #     fail:
    #       message: Can't pull the images
    #     pass:
    #       message: Connected to docker registry
    - customResourceDefinition:
        customResourceDefinitionName: rook
        outcomes:
          - fail:
              message: You don't have rook installed
          - pass:
              message: Found rook!
