apiVersion: troubleshoot.replicated.com/v1beta1
kind: Preflight
metadata:
  name: sample
spec:
  collectors:
    - mysql:
        collectorName: my-mysql
        uri: postgresql://doadmin:nokq949a9dom9qyx@postgres-test-do-user-1634526-0.a.db.ondigitalocean.com:25060/defaultdb?sslmode=require
  analyzers:
    - mysql:
        checkName: Must be postgres 10.x or later
        collectorName: pg
        outcomes:
          - fail:
              when: "connected == false"
              message: Cannot connect to postgres server
          - fail:
              when: "version < 10.x"
              message: The postgres server must be at least version 10
          - pass:
              message: The postgres connection checks out
  