apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: preflight
spec:
  version: "v0.9.5"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/replicatedhq/troubleshoot/releases/download/v0.9.5/preflight_0.9.5_linux_amd64-0.9.5.tar.gz
    sha256: "f6e5fa04d7380961037b287599da9fcb68b0ffca11c44a5aa3ae383709e5a6ff"
    files:
    - from: "./preflight"
      to: "."
    bin: "preflight"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/replicatedhq/troubleshoot/releases/download/v0.9.5/preflight_0.9.5_darwin_amd64-0.9.5.tar.gz
    sha256: "d96e89b2f0b9140f6d7700a3dab94cc13f11d6b39434028177f408c85a5e7105"
    files:
    - from: "./preflight"
      to: "."
    bin: "preflight"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/replicatedhq/troubleshoot/releases/download/v0.9.5/preflight_0.9.5_windows_amd64-0.9.5.zip
    sha256: "83663da417119f3894958028151e2d3981db468ed8b003d2b624e8c17650ed62"
    files:
    - from: "/preflight.exe"
      to: "."
    bin: "preflight.exe"
  shortDescription: Executes application preflight tests in a cluster
  homepage: https://github.com/replicatedhq/troubleshoot
  caveats: |
    Usage:
      $ kubectl preflight <uri/path>

      where <uri/path> references a set of application preflight checks

      For example:

      $ kubectl preflight https://preflight.replicated.com

    For additional options:
      $ kubectl preflight --help

    Documentation:
      Full documentation on this plugin is available at:
      https://help.replicated.com/docs/troubleshoot/kubernetes/preflight/overview/

      For application developers writing collectors and analyzers:
      https://help.replicated.com/docs/troubleshoot/kubernetes/collectors/defining-collectors/

  description: |
    This plugin executes application-specific preflight checks and conformance
    tests against a cluster, prior to installation of an application.

    Application developers can create and host a Preflight manifest that
    defines the minimum and desired Kubernetes environment for an application.
    Before installing the application, a cluster admin can use this plugin to
    execute the application preflight checksto identify any missing
    components, configuration or incompatibilities between the cluster and the
    desired environment.

    When executing Preflight tests, the test results will be displayed in a
    terminal-based UI on the workstation that executed the command.

    For information on creating a Preflight manifest, view the documentation
    at https://help.replicated.com/docs/troubleshoot/kubernetes/analysis/
